// <auto-generated />
using MVCDemoD05.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCDemoD05.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCDemoD05.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentId = 4,
                            Name = "BS"
                        });
                });

            modelBuilder.Entity("MVCDemoD05.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            DepartmentId = 1,
                            Name = "Mohamed",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            DepartmentId = 2,
                            Name = "Ahmed",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            DepartmentId = 3,
                            Name = "Ali",
                            Salary = 6000m
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            DepartmentId = 1,
                            Name = "Sara",
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            DepartmentId = 2,
                            Name = "Mona",
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 6,
                            Age = 30,
                            DepartmentId = 1,
                            Name = "Mohamed",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            DepartmentId = 2,
                            Name = "Ahmed",
                            Salary = 4000m
                        },
                        new
                        {
                            Id = 8,
                            Age = 35,
                            DepartmentId = 3,
                            Name = "Ali",
                            Salary = 6000m
                        },
                        new
                        {
                            Id = 9,
                            Age = 28,
                            DepartmentId = 1,
                            Name = "Sara",
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 10,
                            Age = 32,
                            DepartmentId = 2,
                            Name = "Mona",
                            Salary = 5500m
                        });
                });

            modelBuilder.Entity("MVCDemoD05.Models.Employee", b =>
                {
                    b.HasOne("MVCDemoD05.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MVCDemoD05.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
